name: Go Build

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main

env:
  REGISTRY_STORAGE_DELETE_ENABLED : true

jobs:
  unit-tests:
    concurrency:
      group: kogito_serverless_operator_pr-unit-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 120
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libbtrfs-dev libgpgme-dev libdevmapper-dev
          version: 1.0
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make test

  integration-tests:
    needs: unit-tests
    strategy:
      matrix:
        container-engine:
          - docker
          - podman
          - kaniko-docker
      fail-fast: false
    concurrency:
      group: kogito_serverless_operator_pr-integration-${{ matrix.container-engine }}-${{ github.head_ref }}
      cancel-in-progress: true
    # should be set back to 120 once kogito-swf-builder 1.33 is released
    timeout-minutes: 800
    name: Integration tests (${{ matrix.container-engine }})
    runs-on: ubuntu-22.04
    steps:
      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libbtrfs-dev libgpgme-dev libdevmapper-dev
          version: 1.0
      - name: Install Podman 4.3.1
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/s/shadow/libsubid4_4.11.1+dfsg1-2ubuntu1.1_amd64.deb
          sudo dpkg -i libsubid4_4.11.1+dfsg1-2ubuntu1.1_amd64.deb
          wget http://ftp.us.debian.org/debian/pool/main/libp/libpod/podman_4.3.1+ds1-5+b1_amd64.deb
          sudo dpkg -i podman_4.3.1+ds1-5+b1_amd64.deb
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Display Podman info
        run: podman info
      - name: Start Podman socket
        run: |
          systemctl --user start podman.socket
      - name: Run integration tests
        run: make ${{ matrix.container-engine }}-integration-test